### PR TITLE
fix subnet configuration

### PR DESCRIPTION
**Pull request by michalbagrowski**
fixing our deployment be equal across avalabality zones.

This is destructive change, see CircleCi task for details

### CODE REVIEW

**Comment by michalbagrowski** [comment]
@dincho this change is rotating all static nodes :/

**Comment by dincho** [comment]
@michalbagrowski maybe we should wait until we have proper chain restore in place ?
Is this blocker for some task?

**Comment by michalbagrowski** [comment]
@dincho p.s. this is required by mainnet api gateway. because of issue with creating loadbalancer when subnets are in same avalabality zone

**Comment by dincho** [comment]
So, we merge backup/restore, then this one, then api gateway ?

**Pull request merged**
