### PR TITLE
Add windows artifacts check

### PR DESCRIPTION
**Pull request by venimus**
Should be merged after artifacts are built properly

Note: Windows artifacts are .zip

### CODE REVIEW

**Comment by dincho** [comment]
> Should be merged after artifacts are built properly

not necessary, the check is using the [stable image](https://github.com/aeternity/aeternity/blob/master/.circleci/config.yml#L1071) so this changes will not kick in in the aeternity CI until this repo is tagged

**Comment by venimus** [comment]
Yes, but it might get tagged for some other reason, before the other PR is merged

**Comment by dincho** [comment]
> Yes, but it might get tagged for some other reason, before the other PR is merged

Shouldn't be a problem if you're careful when tagging :)

**Comment by venimus** [comment]
Accidentally pushed something from other branch

**Pull request merged**
